# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title All Sums in C++ (Internal Function)
#' @description Function that prints all combinations of natural numbers that
#' add up to target value.
#' @param target Target value for sum.
#' @return List of combinations that add up to target value.
#' @keywords internal
print_all_sumC <- function(target) {
    .Call(`_lpcde_print_all_sumC`, target)
}

